# Generated by Django 4.0 on 2021-12-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=150, null=True)),
                ('tools', models.CharField(blank=True, max_length=150, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('project_img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
